name: Vale
on:
  pull_request:
    paths:
    - 'docs/en/**/*'

permissions:
  contents: read

# Stop the current running job if a new push is made to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  vale:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Clone DanRoscigno Vale
      uses: actions/checkout@v4
      with:
        repository: DanRoscigno/starrocks-vale
        path: starrocks-vale
        persist-credentials: false

    - name: Debug config file path
      run: |
        find .. -type f -name "*vale.ini"

    - name: Debug style dir path
      run: |
        find .. -type d -name styles

    #- name: Edit StylesPath in Vale config file
      #run: sed -i 's/\.\.\/starrocks-vale\/styles/\.\/starrocks-vale\/styles/' ./docs/.vale.ini

    - name: Find changed lines
      id: changed_lines
      uses: hestonhoffman/changed-lines@v1
      with:
        file_filter: '.md, .mdx'
      
    - name: run-vale
      uses: errata-ai/vale-action@reviewdog
      if: steps.changed_lines.outputs.changed_files
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review
        files: ${{steps.changed_lines.outputs.changed_files}}
        fail_on_error: true
        token: ${{secrets.GITHUB_TOKEN}}
        vale_flags: "--config=./starrocks-vale/vale.ini"
