name: Vale
on:
  pull_request:
    paths:
    - 'docs/en/**/*'

permissions:
  contents: read

# Stop the current running job if a new push is made to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  vale:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Clone DanRoscigno Vale
      uses: actions/checkout@v4
      with:
        repository: DanRoscigno/starrocks-vale
        path: starrocks-vale
        persist-credentials: false
    
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
    - run: pip install vale==3.9.1

    - name: Debug config file path
      run: find -type f -name .vale.ini

    - name: Edit StylesPath in Vale config file
      run: sed -i 's/\.\.\/starrocks-vale\/styles/starrocks-vale\/styles/' ./docs/.vale.ini
           
    - name: Find changed lines
      id: changed_lines
      uses: hestonhoffman/changed-lines@v1
      with:
        file_filter: '.md, .html'
  
    - name: Run vale on changed files
      if: steps.changed_lines.outputs.changed_files
      env: 
        CHANGED_FILES: ${{ steps.changed_lines.outputs.changed_files }}
      run: |
        vale --config="./docs/.vale.ini" "${CHANGED_FILES}" \
          --output=local/bin/py/vale/vale_template.tmpl --no-exit > vale_output.log

    - name: Parse Vale output
      if: steps.changed_lines.outputs.changed_files
      env:
        CHANGED_LINES: ${{ steps.changed_lines.outputs.changed_lines }}
      run: |
        python local/bin/py/vale/vale_annotations.py \
          --git_data="${CHANGED_LINES}"
